opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - file_name
  - file_name_no_space
  - file_types_order
  - final_test_case
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - cyclomatic_complexity
  - todo
  - type_body_length
  - trailing_comma
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment

identifier_name:
  allowed_symbols: [_]
  excluded:
    - i
    - l
    - r
    - p
    - x
    - y
    - ch
    - fm
    - li
    - re
    - vi

# exclude names using in generics
type_name:
  excluded:
    - T

analyzer_rules:
  - unused_import

force_cast: warning
force_try: warning

function_body_length:
    warning: 100

legacy_hashing: error

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  excluded_lines_patterns:
    # String format
    - 'NSLocalizedString\('
    - 'String\.localizedStringWithFormat\('
    - 'String\(format'
    - 'format: ".*",$'
    - 'fatalError\('
    - 'NSLog\('
    - 'print\('
    - 'NSPredicate\(format'

    # Constraints
    - 'constraint\(equalTo'

    # App Specific
    - 'folder-\d+(-open)?'
    - 'FileSizeFormatter\.default'

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2
