name: 🐞 Bug Report
description: Template for reporting a bug
labels: ["bug"]
body:
  - type: textarea
    id: what_happens
    attributes:
      label: What happens?
      description: Describe the current behavior clearly
      placeholder: The app crashes when...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what the correct behavior should be
      placeholder: I expected that...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the steps needed to reproduce the issue
      placeholder: |
        1. Open the app
        2. Click on "X"
        3. ...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your system
      placeholder: |
        - OS:
        - App version:
        - Device:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots (optional)
      description: Attach logs, screenshots, or error messages if possible
